name: Pull Request Checks

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js project
        uses: ./.github/actions/setup-node-project

      - name: Run linter
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Run unit tests
        uses: ./.github/actions/run-unit-tests

  e2e-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Run E2E tests
        uses: ./.github/actions/run-e2e-tests
        with:
          supabase-url: ${{ secrets.SUPABASE_URL }}
          supabase-key: ${{ secrets.SUPABASE_KEY }}
          supabase-service-role-key: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          e2e-username-id: ${{ secrets.E2E_USERNAME_ID }}
          e2e-username: ${{ secrets.E2E_USERNAME }}
          e2e-password: ${{ secrets.E2E_PASSWORD }}
